services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_SERVE_ARTIFACTS=true
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - app-models:/app/models
      - mlflow-data:/mlflow
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=8000"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=dracula
    depends_on:
      - postgres
    networks:
      - backend-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - backend-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-lokiexplore-app
      - GF_PLUGIN_UPDATE_CHECK_ENABLED=false
      - GF_PLUGIN_UPDATE_CHECK_INTERVAL=0
      - GF_PLUGIN_UPDATE_CHECK_TIMEOUT=0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://postgres:postgres@postgres:5432/mlflow --default-artifact-root file:///mlflow/artifacts --serve-artifacts
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_SERVE_ARTIFACTS=true
      - PYTHONPATH=/app
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app-models:/app/models
      - mlflow-data:/mlflow
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    dns:
      - 8.8.8.8
      - 8.8.4.4

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: airflow webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:postgres@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_SERVE_ARTIFACTS=true
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - app-models:/app/models
      - mlflow-data:/mlflow
    networks:
      - backend-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:postgres@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_ARTIFACT_ROOT=file:///mlflow/artifacts
      - MLFLOW_SERVE_ARTIFACTS=true
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - app-models:/app/models
      - mlflow-data:/mlflow
    networks:
      - backend-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: airflow,mlflow,fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-postgresql.sh:/docker-entrypoint-initdb.d/init-postgresql.sh
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus-data:
  grafana-data:
  mlflow-data:
  app-models: